pointless:
  - web.asd dot.com
  - webasd\tdot.com
  - random
  - http://
  - http:/
  - http://.com
  - http://ssh://google.com
  - http://ftp://ftp.google.com
  - <>hi
  - www.vsdfbdfsbsdfbsdnflbsdfjnbfldsjbnsdlfbndjlsfnblsdjfkbnlsdfknbklsdfjbnlsjdkfbnsjkdlfbnkjsdlfnbklsdfnbklsdfnbklsdfjbnksdjlfbnklsdfjbnlkjsdfnbklsdjfbnlkjsdfbnjfdsvsdkfjnbjdksfnbdslkfjbnjsdfklbnsdjkflbnjsdfbndsbfdfb.com
  - http://www.sdfbnldsnfjbldsfjkbnldksfjbnlkdfjnblkd.fsjnblkdfsjbndfljkvnsfdj.bkndsfkljbnsljdkbnsdflkbjnsdflk.bjnsldfkjbn.ldksfjbnlksdfjnblksdfnb.lsdkfjbndsflkjbndsflkbjndslfkbnldsfkj.bnkjsldfnblksdfjbnlsdkfn.bldskfjbnldskfbndlsf.kbjndflkbndfslkbnjdsfblkdsjfn.bldskfnblsdfnbjksdflkbnj.org

misprints:
  - htt://www.website.com
  - htttp://www.website.com
  - http://example.com.
  - http://example.com./foo
  - http://ex ample.com
  - http://example com
  - http:/www.google.com
  - http://example.com/foo bar
  - http://r?ksmorgas.com

local:
  - http://localhost
  - https://localhost

unsupported_protocols:
  - ftp://website.com
  - new://www.website.com
  - ftp://www.詹姆斯
  - ftp://localhost
  - ssh://google.com
  - ftp://ftp.google.com
  - ftp://username:password@hostname.com/
